version: "3.9"

services:

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    command: gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4
    volumes:
      - ./backend:/code
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
      - REDIS_URL=redis://redis:6379
      - DJANGO_SECRET_KEY=your_production_secret_key
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    command: sh -c "npm install && npm run build && cp -r dist/* /usr/share/nginx/html"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:
  redis_data:
