name: ae-tools-backend
services:
  - name: backend
    github:
      repo: AemonGames/Neo-AE-Tools
      branch: main
      deploy_on_push: true
    source_dir: backend  # ✅ this is the correct key
    run_command: gunicorn backend.wsgi
    build_command: pip install -r requirements.txt
    envs:
      - key: DJANGO_SECRET_KEY
        value: "${DJANGO_SECRET_KEY}"
      - key: GOOGLE_OAUTH_CLIENT_ID
        value: "${GOOGLE_OAUTH_CLIENT_ID}"
      - key: DATABASE_URL
        value: "${DATABASE_URL}"
      - key: ALLOWED_HOSTS
        value: api.yourdomain.com
      - key: DEBUG
        value: "false"
    instance_size_slug: basic-xxs
    routes:
      - path: /
